color = input("Enter a color: ")
animal = input("Enter an animal: ")
body_part = input("Enter in a body part: ")
plural_noun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity name: ")
verb_ed = input("Enter a verb (past tense): ")
noun = input("Enter a noun (plural): ")
noun_1 = input("Enter a noun (plural): ")
adjective = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
adjective_2 = input("Enter in an adjective: ")
saying = input("Enter in an expression: ")
print("I was walking down the " + color + " street yesterday, ")
print("when I saw a huge " + animal + " on the sidewalk.")
print("I couldn't believe my eyes!  When I got closer I saw it had a really big " + body_part + ".")
print(plural_noun + "! I exclaimed!!")
print("I walked over to the " + animal + " and saw it had collar with a nametag. It said " + celebrity + " .")
print("I wondered where the animal had come from. Did it live in a house? I " + verb_ed + " everywhere but could not see anyone nearby.")
print("I took a closer look at " + celebrity + " the " + animal + "and noticed they were wearing 20 glittery " + noun + " and ")
print("ten flaming " + noun_1 + "!")
print("This was the most " + adjective + " " + animal + " I had ever seen in my entire life!")
print("I " + adverb + " took a picture of this strange sight and ran all the way back to my " + adjective_2 + " house.")
print(saying + "! What a weird day!!!")
